### ISSUE TITLE
Launch issues

### ISSUE THREAD

**Issue by fdbgbgsf** [chrisgahlert/jdownloader2-vnc#1]
I'm currently incabable of launching this container, it crashes during launch. In the log I get a lot of the following.

```
groupdel: cannot remove the primary group of user 'jd2'
group jd2 does not exist
groupadd: group 'jd2' already exists
group jd2 already exists
useradd: group 'jd2' does not exist
user jd2 already exists
Xvfb: no process found
nohup: appending output to 'nohup.out'
chown: invalid user: 'jd2:jd2'
error: failed switching to &quot;jd2&quot;: Unable to find user jd2
```

I had some issues in the beginning, but got it launched, but foolishly decided to restart for updates.

Running latest versions of everything on Synology NAS.

Any advice? Thanks.

**Comment by chrisgahlert** [comment]
Sorry for the late response... I didn't notice this issue!

In case you are still interested: It should be fixed now and a new image has been pushed. ;)
