### ISSUE TITLE
The default path in jdownloader is not set to /download

### ISSUE THREAD

**Issue by elboletaire** [chrisgahlert/jdownloader2-vnc#2]
First off, excellent container! I used to configure this manually and today needed to due it but you saved my day :)

After configuring it, and without specifying a custom config path, the downloads are stored in `/usr/?/Downloads` instead of in `/download`.

Can you do something with that? Or should we point to `/usr/?/Downloads` instead of to `/download`?

**Comment by chrisgahlert** [comment]
Yes, the default path should be fixed. For now you can manually configure it to whatever you like:

![jd2](https://cloud.githubusercontent.com/assets/1876381/21421661/576bb7e6-c834-11e6-91c5-ba0cb080513c.png)

**Comment by elboletaire** [comment]
That's what I've done 😃

**Comment by elboletaire** [comment]
:+1:
