### ISSUE TITLE
Launch issues 2

### ISSUE THREAD

**Issue by fdbgbgsf** [chrisgahlert/jdownloader2-vnc#3]
In continuation of [Launch issues](https://github.com/chrisgahlert/jdownloader2-vnc/issues/1).

I've redownloaded the image (had previously deleted everything container due to issues) and have been using it for a couple of weeks, once restarted due to system update and it took a couple of tries to get the container launched. Today I've attempted to start the container 25 times without succes.

[Logs of the final attempt here](http://pastebin.com/jDfjg7ZJ).

**Comment by chrisgahlert** [comment]
Can you confirm that this resolves your problem?

**Comment by fdbgbgsf** [comment]
Just tried to do an update and it keeps failing to launch :(

**Comment by fdbgbgsf** [comment]
So, the way I've found around this problem is to clear the container and the /app folder, launch, stop, restore /app/cfg and launch (a couple of times as it still fails).
Then it works fine again, until the next restart of the container…
